spec:
  inputs:
    kube_context:
      description: "kubectl context (kubeconfig entry) to target"
      type: string
    applyset:
      description: "Suffix for the ApplySet label"
      default: "default"
      type: string
    manifest:
      description: "Path (file or directory) of CRD manifests"
      default: "k8s"
      type: string

---

stages:
  - deploy

crd_apply:
  stage: deploy
  image:
    name: alpine/k8s:1.33.0      # pin digest in production
    entrypoint: [ "" ]
  script:
    - export KUBECTL_APPLYSET=true
    - echo "Applying CRDs with applyset=crd-$[[ inputs.applyset ]]"
    - |
      kubectl apply \
        -n default \
        --prune \
        --applyset="crd-$[[ inputs.applyset ]]" \
        --force-conflicts \
        --server-side \
        --context="$[[ inputs.kube_context ]]" \
        --validate=false \
        -f "$[[ inputs.manifest ]]"
  tags:
    - gitlab-org-docker
